kind: Service
apiVersion: v1
metadata:
  name: websocket
  namespace: shopping
  labels:
    app.kubernetes.io/name: websocket
    app.kubernetes.io/version: v1.0
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      #port: 8080
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: websocket