kind: Deployment
apiVersion: apps/v1
metadata:
  name: store-websocket
  namespace: shopping
  labels:
    app.kubernetes.io/name: store-websocket
    app.kubernetes.io/version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: store-websocket
      app.kubernetes.io/version: v1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: store-websocket
        app.kubernetes.io/version: v1.0
    spec:
      containers:
        - name: store-websocket
          image: localhost:5000/go-shopping-poc/websocket:1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP