apiVersion: v1
kind: ConfigMap
metadata:
  name: eventwriter-config
  namespace: shopping
  labels:
    app: go-shopping-poc
    component: eventwriter
data:
  # EventWriter Service Settings
  EVENT_WRITER_WRITE_TOPIC: "ReaderEvents"
  EVENT_WRITER_READ_TOPICS: ""
