apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: postgres
  labels:
    app: go-shopping-poc
    component: postgresql
data:
  POSTGRES_DB: "postgresdb"
  POSTGRES_USER: "postgresadmin"
