apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: shopping
  labels:
    app: go-shopping-poc
    component: product
data:
  # Product Service Port
  PRODUCT_SERVICE_PORT: ":8081"

  # Product Service Kafka Settings
  PRODUCT_WRITE_TOPIC: "ProductEvents"
  PRODUCT_GROUP: "ProductGroup"

  # MinIO Bucket (for event publishing)
  MINIO_BUCKET: "productimages"
