apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: store-eventreader
  namespace: shopping
  labels:
    app.kubernetes.io/name: store-eventreader
    app.kubernetes.io/version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: store-eventreader
      app.kubernetes.io/version: v1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: store-eventreader
        app.kubernetes.io/version: v1.0
    spec:
      containers:
        - name: store-eventreader
          image: localhost:5000/go-shopping-poc/eventreader:1.0
          imagePullPolicy: Always