kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: store-customer-ingress
  namespace: shopping
  labels:
    app.kubernetes.io/name: store-customer-ingress
    app.kubernetes.io/version: v1.0
  annotations:
    #nginx.ingress.kubernetes.io/auth-tls-secret: "shopping/pocstorelocal-tls"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
    # If you need client TLS authentication you can define a TLSOption CRD and reference it:
    #traefik.ingress.kubernetes.io/router.tls.options: pocstorelocal-client-auth@kubernetescrd
spec:
  rules:
    - host: pocstore.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-customer-svc
                port:
                  number: 80
  tls:
  - hosts:
    - pocstore.local
    secretName: pocstorelocal-tls