apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: store-customer
  namespace: shopping
  labels:
    app.kubernetes.io/name: store-customer
    app.kubernetes.io/version: v1.0
spec:
  serviceName: store-customer-svc
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: store-customer
      app.kubernetes.io/version: v1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: store-customer
        app.kubernetes.io/version: v1.0
    spec:
      containers:
        - name: store-customer
          image: localhost:5000/go-shopping-poc/customer:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-customer-svc
  namespace: shopping
  labels:
    app.kubernetes.io/name: store-customer-svc
    app.kubernetes.io/version: v1.0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: store-customer
    app.kubernetes.io/version: v1.0
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-customer-ingress
  namespace: shopping
  labels:
    app.kubernetes.io/name: store-customer-ingress
    app.kubernetes.io/version: v1.0
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
spec:
  rules:
    - host: pocstore.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-customer-svc
                port:
                  number: 80
  tls:
    - hosts:
        - pocstore.local
      secretName: pocstorelocal-tls