kind: Deployment
apiVersion: apps/v1
metadata:
  name: store-customer
  namespace: shopping
  labels:
    app.kubernetes.io/name: store-customer
    app.kubernetes.io/version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: store-customer
      app.kubernetes.io/version: v1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: store-customer
        app.kubernetes.io/version: v1.0
    spec:
      containers:
        - name: store-customer
          image: localhost:5000/go-shopping-poc/customer:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080