apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventreader
  namespace: shopping
  labels:
    app.kubernetes.io/name: eventreader
    app.kubernetes.io/version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eventreader
      app.kubernetes.io/version: v1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eventreader
        app.kubernetes.io/version: v1.0
    spec:
      containers:
        - name: eventreader
          image: localhost:5000/go-shopping-poc/eventreader:1.0
          imagePullPolicy: Always
          env:
            # Platform config (selective)
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: LOG_LEVEL

            # Service config (selective)
            - name: EVENT_READER_WRITE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: eventreader-config
                  key: EVENT_READER_WRITE_TOPIC
            - name: EVENT_READER_READ_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: eventreader-config
                  key: EVENT_READER_READ_TOPICS
            - name: EVENT_READER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: eventreader-config
                  key: EVENT_READER_GROUP

            # Platform Kafka settings
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: KAFKA_BROKERS
